const axios = require('axios');

exports.analyzeText = async (text) => {
    const systemPrompt = `You are a sophisticated AI text classification engine (similar to GPTZero). 
Analyze the provided text and determine the probability (0-100) that it was generated by an AI like ChatGPT, Gemini, or Claude.
Evaluate the text strictly based on: robotic tone, highly predictable phrasing (low perplexity), repetitive sentence structures, repetitive transition words (Like "Furthermore", "In conclusion"), and lack of human burstiness.
You MUST format your output strictly as a JSON object exactly like this:
{
  "ai_probability": 85,
  "reason": "Short concise sentence explaining why the structural variance feels artificial or natural."
}`;

    try {
        const response = await axios.post(
            "https://api.groq.com/openai/v1/chat/completions",
            {
                model: "llama-3.3-70b-versatile",
                messages: [
                    { role: "system", content: systemPrompt },
                    { role: "user", content: `Please thoroughly analyze this text for AI generation: ${text}` }
                ],
                response_format: { type: "json_object" },
                max_tokens: 300,
                temperature: 0.1
            },
            {
                headers: {
                    Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
                    "Content-Type": "application/json",
                },
                timeout: 30000,
            }
        );

        const content = response.data?.choices?.[0]?.message?.content;

        let parsed;
        try {
            parsed = JSON.parse(content);
        } catch (e) {
            console.error("JSON Parse failure from AI", content);
            parsed = { ai_probability: 0, reason: "Fallback extraction failed." };
        }

        return {
            similarity: parsed.ai_probability || 0,
            reason: parsed.reason || "Analyzed via Groq linguistic variance architecture.",
            method: "Llama-3-70B Classification"
        };
    } catch (err) {
        console.error("AI Detector Error:", err.response?.data || err.message);
        throw err;
    }
};
